database:
  image: postgres

redis:
  image: redis
  ports:
  - "6379:6379"

worker:
  build: .
  volumes:
    - .:/code
  environment:
   - DEBUG=True
   - C_FORCE_ROOT=True
  links:
   - database
   - redis
  command: python /code/manage.py celeryd -l DEBUG

uwsgi:
  build: .
  volumes:
    - .:/code
  links:
   - database
   - redis
  ports:
   - "80:8000"
   - "8000:8000"
  environment:
   - DEBUG=True
  command: python /code/manage.py runserver 0.0.0.0:8000 # Debug